-keep class com.rev4n.unlimitedphotos.EntryPoint {public <methods>;}
-keep class com.rev4n.unlimitedphotos.CustomProvider
-keep class com.rev4n.unlimitedphotos.CustomKeyStoreSpi
-keep class com.rev4n.unlimitedphotos.CustomPackageInfoCreator
